name: IpacChatFilter
version: '1.0-SNAPSHOT'
main: io.github.aplini.ipacChatFilter.IpacChatFilter
api-version: '1.20'
authors: [ ApliNi ]
website: https://github.com/aplini/

permissions:
  IpacChatFilter.filter:
    description: 启用消息过滤
    default: true
  IpacChatFilter.bypass:
    description: 绕过消息过滤
    default: false

commands:
  icf:
    description: IpacChatFilter 插件的主命令
    usage: /<command>
